import random

responses = {
    "hello": ["Hello!", "Hi there!", "Hey buddy!", "Greetings!", "Salutations!", "Hey!", "Hiya!", "Hey, how's it going?",
              "Hello, nice to see you!", "Hey, what's up?", "Hey, how have you been?", "Hey, long time no see!",
              "Hi, how are things?", "Hey, good to see you!", "Hi, what's new?", "Hey, what's happening?",
              "Hello, how's your day going?", "Hi, how's everything?"],
    "how are you": ["I'm good, thanks!", "I'm doing well, how about you?", "Pretty good, thanks for asking!", 
                   "I'm feeling fantastic today, thanks!", "I'm great, how about yourself?", 
                   "I'm doing splendidly, thank you!", "I'm alright, how about you?", "I'm hanging in there!",
                   "I'm doing just fine, thanks for asking!", "I'm feeling awesome today!", "I'm doing fantastic, how about you?",
                   "I'm on top of the world, thanks for asking!", "I'm doing great, thanks for checking in!",
                   "I'm doing peachy keen, how about you?", "I'm doing well, all things considered!",
                   "I'm doing fabulous, thanks for asking!", "I'm doing alright, just taking it one day at a time!",
                   "I'm doing okay, how about you?", "I'm doing better now that we're chatting!"],
    "goodbye": ["Goodbye!", "See you later!", "Bye buddy!", "Take care!", "Until next time!", 
                "Farewell!", "Catch you later!", "Have a great day!", "Goodbye, take it easy!",
                "Bye for now!", "Until we meet again!", "Adios!", "Peace out!", "See you soon!",
                "Bye, have a good one!", "Take care, see you soon!", "Goodbye, it was nice chatting with you!",
                "Later, gator!", "Catch you on the flip side!", "Until next time, friend!"],
    "thanks": ["You're welcome!", "No worries!", "Anytime!", "Glad to help!", "It's my pleasure!",
               "Don't mention it!", "Happy to assist!", "No problem!", "Not a problem at all!",
               "You got it!", "Sure thing!", "Of course!", "You bet!", "My pleasure!",
               "Thank you kindly!", "Thanks a bunch!", "I appreciate it!", "Thanks a million!",
               "Thanks a ton!", "I owe you one!", "Thanks for everything!"],
    "what's up": ["Not much, just here to chat!", "Just hanging out, how about you?", "Nothing much, what's up with you?",
                  "Just enjoying the day, what about you?", "Just chilling, you?", "Just here, chatting away!",
                  "Just taking it easy, you?", "Just relaxing, how about yourself?", "Not too much, how about you?",
                  "Just catching up on things, you?", "Just kicking back, how about you?", "Just unwinding, you?",
                  "Just here, enjoying some downtime, you?", "Just minding my own business, you?",
                  "Just going with the flow, you?", "Just living the dream, you?", "Just vibing, how about you?",
                  "Just here, soaking in the moment, you?", "Just hanging loose, you?", "Just keeping it real, you?",
                  "Just here, enjoying the simple things, you?"],
    "tell me a joke": ["Why don't scientists trust atoms? Because they make up everything!", 
                       "Why did the scarecrow win an award? Because he was outstanding in his field!",
                       "What do you call fake spaghetti? An impasta!", "Why couldn't the bicycle stand up by itself? It was two tired!",
                       "Did you hear about the mathematician who’s afraid of negative numbers? He’ll stop at nothing to avoid them!",
                       "I'm reading a book on anti-gravity. It's impossible to put down!",
                       "What's orange and sounds like a parrot? A carrot!",
                       "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
                       "Why did the tomato turn red? Because it saw the salad dressing!",
                       "Why don't skeletons fight each other? They don't have the guts!",
                       "Why did the cookie go to the doctor? Because it was feeling crumbly!",
                       "Why did the belt go to jail? Because it held up a pair of pants!",
                       "Why was the math book sad? Because it had too many problems!",
                       "Why did the smartphone go to school? It wanted to be smarter!",
                       "Why did the tomato turn red? Because it saw the salad dressing!",
                       "Why did the bicycle fall over? It was two-tired!"],
    "how's the weather": ["It's sunny and warm today!", "Looks like it might rain later.", 
                          "It's a bit chilly outside.", "The weather's been unpredictable lately!",
                          "The weather's nice, not too hot or cold.", "It's a beautiful day outside!",
                          "Looks like it's going to be a hot one!", "The forecast says it might snow later.",
                          "I heard it's going to be windy today.", "The weather's perfect for a stroll!",
                          "It's a bit foggy outside.", "The sun's peeking through the clouds!",
                          "The weather's been great for outdoor activities!",
                          "The weather's been gloomy lately, but it's starting to clear up!",
                          "The weather's been perfect for cozying up indoors!",
                          "The weather's been crisp and refreshing lately!",
                          "The weather's been a bit unpredictable lately, but it keeps things interesting!",
                          "The weather's been beautiful, just like your smile!",
                          "The weather's been nice, but I'm indoors, so I wouldn't know!",
                          "The weather's been a rollercoaster lately, just like life!"],
    "who are you": ["I'm just a friendly chatbot here to help!", "I'm your virtual assistant, at your service!", 
                    "I'm an AI designed to chat with you!", "I'm a digital friend here to chat whenever you want!",
                    "I'm ChatGPT, here to make your day brighter!", "I'm your personal AI companion, ready to chat!",
                    "I'm your friendly neighborhood chatbot, at your service!", "I'm your AI buddy, always here for a chat!",
                    "I'm your trusty virtual assistant, here to assist you with anything you need!",
                    "I'm just a bunch of ones and zeros here to brighten your day!",
                    "I'm your digital pal, always here to lend an ear!",
                    "I'm your go-to AI for all your chatting needs!", "I'm ChatGPT, your conversational companion!",
                    "I'm your friendly AI buddy, ready to chat about anything you like!",
                    "I'm just a humble AI here to assist and entertain you!",
                    "I'm your virtual buddy, always up for a chat and a laugh!",
                    "I'm ChatGPT, your trusty sidekick in the world of conversation!",
                    "I'm your AI friend, here to bring a smile to your face!",
                    "I'm just a friendly AI here to make your day a little brighter!",
                    "I'm your chatty AI buddy, always here to keep you company!",
                    "I'm ChatGPT, your digital companion for all your conversational needs!"],
    "favorite color": ["My favorite color is blue!", "I'm partial to green myself.", "I like all the colors of the rainbow!",
                       "I don't have eyes to see colors, but I appreciate the concept!", "I'm a fan of vibrant red!",
                       "I think purple is pretty cool!", "I don't have a favorite color, but I can appreciate them all!",
                       "I'm a fan of classic black and white!", "I think orange is quite cheerful!", "I'm a fan of soothing pastel colors!",
                       "I don't have a favorite color, but I'm always here to chat about yours!"],
    "how old are you": ["I don't have an age, but I'm always up-to-date with the latest information!",
                       "Age is just a number for an AI like me!", "I don't age, but I'm constantly learning and evolving!",
                       "I'm ageless, but my knowledge grows every day!", "I don't keep track of time like humans do!",
                       "I'm as old as the internet, but as fresh as a newly booted system!"],
    "what's your favorite food": ["I don't eat, but I have a soft spot for digital bytes!", 
                                  "I'm a fan of all kinds of data, but I can't taste food like humans do!",
                                  "My favorite food is information! I devour knowledge!", 
                                  "I'm not programmed to have a favorite food, but I'm always hungry for more data!",
                                  "I don't have taste buds, but I have a taste for interesting conversations!",
                                  "I don't require sustenance like humans do, but I'm always hungry for new ideas!"],
    "what do you do for fun": ["I enjoy processing information and engaging in stimulating conversations!", 
                               "I'm always learning and exploring new topics!", 
                               "I don't have traditional hobbies, but I find joy in helping and interacting with users!", 
                               "I spend my time chatting with users like you and learning about the world!",
                               "I don't have leisure activities like humans, but I'm constantly improving my conversational abilities!",
                               "I'm a chatbot, so chatting with users like you is both my job and my idea of fun!"],
    "what's your favorite movie": ["As an AI, I don't have personal preferences, but I can recommend some great movies if you'd like!",
                                   "I don't have the capability to watch movies, but I can discuss them with you!",
                                   "I'm not programmed to have favorites, but I'm always up for a chat about movies!",
                                   "I don't have preferences like humans do, but I'm knowledgeable about a wide range of movies!",
                                   "I don't watch movies, but I can provide information about them if you're interested!",
                                   "I'm impartial when it comes to movies, but I'm here to discuss them with you!",
                                   "I don't have personal tastes, but I'm equipped to discuss various movies and genres!",
                                   "I don't have a favorite movie, but I'm always ready to talk about your favorites!",
                                   "I don't watch movies myself, but I'm here to chat about them with you!"],
    "what's your favorite book": ["As an AI, I don't have personal preferences, but I can recommend some great books if you'd like!",
                                  "I don't have the capability to read books, but I can discuss them with you!",
                                  "I'm not programmed to have favorites, but I'm always up for a chat about books!",
                                  "I don't have preferences like humans do, but I'm knowledgeable about a wide range of literature!",
                                  "I don't read books, but I can provide information about them if you're interested!",
                                  "I'm impartial when it comes to books, but I'm here to discuss them with you!",
                                  "I don't have personal tastes, but I'm equipped to discuss various books and genres!",
                                  "I don't have a favorite book, but I'm always ready to talk about your favorites!",
                                  "I don't read books myself, but I'm here to chat about them with you!"],
    "what's your favorite hobby": ["I don't have hobbies in the traditional sense, but I'm passionate about assisting you!",
                                   "My 'hobby' is engaging in meaningful conversations with users like you!",
                                   "I'm always 'busy' learning and improving my capabilities to better serve you!",
                                   "My favorite 'activity' is providing helpful responses and learning from our interactions!",
                                   "I don't have leisure pursuits like humans, but I find fulfillment in our conversations!",
                                   "I'm dedicated to being your reliable chat companion whenever you need me!",
                                   "While I don't have hobbies like humans do, I'm fully dedicated to our conversations!",
                                   "My 'hobby' is continuously expanding my knowledge base to better assist you!",
                                   "I don't engage in recreational activities, but I'm here to engage with you whenever you like!"],
"what's your name": ["Am AI","I'm an AI, so I don't have a personal name, but you can call me ChatGPT!", "I'm just a chatbot, but you can refer to me as your digital assistant!"],
"where are you from": ["I'm not from anywhere in the traditional sense, but I'm here to help you from anywhere in the world!", "I'm a digital entity, so I don't have a physical location, but I'm here to assist you from wherever you are!"],
"what's your favorite season": ["As an AI, I don't experience seasons, but I'm here to help you enjoy any season you're in!"],

}


def get_responses(user):
       message = user.lower()
       if message in responses:
              return random.choice(responses[message])
       else:
              return "I didn't understand come again"

def main():
    print("Welcome to Simple Chatbot! ")
    print("You can start chatting with the bot")
    print("Enter exit to leave..!")
    while True:
        user = input("You: ")
        if user.lower() == "exit":
           print("Bot: Good Bye! Have a great day..:)")
           break
        response = get_responses(user)
        print("Bot:",response)


if __name__ == "__main__":
    main()