name: Azure Login and Workflow

on:
  push:
    branches:
      - main

jobs:
  azure-login-and-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_25B70C8C12774DA2BA313899DBDBF26E }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2ac36cee-0617-4ac0-bebf-e1ce5dfab86c }}

    - name: Run Your Azure Commands
      run: |
        # Add your Azure CLI or Azure PowerShell commands here
        # For example:
        # az group list

    - name: Send Email Notification on Failure
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.your-email-provider.com
        server_port: 587
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.PASS }}
        subject: Workflow Failure Notification
        body: |
          Hello Team Stars,
          
          The workflow failed. Please check the logs for more details.
          
          Regards,
          Your CI/CD System
        to: burugunithin1@gmail.com
        from: ${{ secrets.EMAIL }}
