# name: Build, Deploy, and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'nventory'
          slot-name: 'Production'

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/Inventory_Management.postman_collection.json \
            --env-var "baseUrl=https://nventory.azurewebsites.net" \
            --reporters cli,json \
            --reporter-json-export results/report.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: results/report.json

  send-email:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Postman Test Results
          body: |
            Hello Team,

            Please find attached the Postman test report. The deployment was completed successfully, and the test results are as follows:

            {{ steps.newman-run.outputs.test-summary }}

            Regards,
            Your CI/CD System
          to: team@example.com
          from: no-reply@example.com
          content_type: text/html
          attachments: results/report.json
