name: Build and deploy Python app to Azure Web App - nventory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D18BE59980CF49E4B5458BD28CF71476 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB8C1BF1485242E198CB2979B428519C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C272F2CC01974200959930821675DD1B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'nventory'
          slot-name: 'Production'

  test:
    runs-on: ubuntu-latest
    needs: deploy

    outputs:
      tests-passed: ${{ steps.parse-results.outputs.tests-passed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/Inventory_Management.postman_collection.json --reporters cli,json --reporter-json-export results/report.json --env-var baseURL=https://nventory.azurewebsites.net

      - name: Parse Test Results
        id: parse-results
        run: |
          tests_failed=$(jq '.run.failures | length' results/report.json)
          if [ "$tests_failed" -eq 0 ]; then
            echo "All tests passed."
            echo "::set-output name=tests-passed::true"
          else
            echo "Tests failed."
            echo "::set-output name=tests-passed::false"
          fi

  send-email:
    runs-on: ubuntu-latest
    needs: [deploy, test]
    if: always() # Ensure this job runs regardless of success or failure

    steps:
      - name: Determine Email Subject and Body
        id: prepare-email
        run: |
          if [ "${{ needs.test.outputs.tests-passed }}" == "true" ]; then
            echo "subject=Postman Test Results and Deployment Status" >> $GITHUB_ENV
            echo "body=Hello Team Stars,\n\nAll Postman tests passed, and the deployment was successful.\n\nRegards,\nYour CI/CD System" >> $GITHUB_ENV
          else
            echo "subject=Workflow Failure Notification" >> $GITHUB_ENV
            echo "body=Hello Team Stars,\n\nThe workflow failed. Please check the logs for more details.\n\nRegards,\nYour CI/CD System" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587 # or 465 for SSL
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASS }}
          subject: ${{ env.subject }}
          body: ${{ env.body }}
          to: burugunithin1@gmail.com
          from: nithinjashua1@gmail.com
