# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build, test, deploy, and notify for Python app - nventory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install pytest
        run: |
          source venv/bin/activate
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --junitxml=reports/test-results.xml  # Generate test results in JUnit format

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy_test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App Test Slot'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'nventory'
          slot-name: 'test'

  deploy_production:
    runs-on: ubuntu-latest
    needs: [build, deploy_test]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App Production Slot'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'nventory'
          slot-name: 'production'

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy_test, deploy_production]

    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/reports/test-results.xml'
          fail_on_failure: false
          check_name: Test Report

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com  # replace with your SMTP server
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASS }}
          subject: Build and Deployment Notification
          body: |
            The build and deployment process has completed.
            - Build Status: ${{ job.status }}
            - Test Report: ${{ steps.publish.outputs.test-report-url }}
          to: burugunithin1@gmail.com
          from: nithinjashua1@gmail.com
